<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reports</name>
   <tag></tag>
   <elementGuidId>005d3ab2-c5e5-4e8a-85b1-7f60ce4c2f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-center-navbar']/nav/ul/li[5]/a/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36bd66cc-3943-4f29-9685-e68668137e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item-label</value>
      <webElementGuid>e174808b-46d0-4ba1-b514-73b8888e038d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>85dc84c4-070d-408b-8f50-58d06338f90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-center-navbar&quot;)/nav[@class=&quot;custom-navbar testops-theme expanded navbar&quot;]/ul[@class=&quot;sidebar-main navbar-nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/a[1]/span[@class=&quot;nav-item-label&quot;]</value>
      <webElementGuid>770eeaa0-c641-4236-8abb-4dc7d17f343c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-center-navbar']/nav/ul/li[5]/a/a/span</value>
      <webElementGuid>79281373-14fd-4d35-b4c8-ba198473bde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Executions'])[1]/following::span[1]</value>
      <webElementGuid>1d82e21d-ba77-4a27-8c6f-0e1471b15947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tests'])[1]/following::span[2]</value>
      <webElementGuid>746f0880-89ed-4d86-82b1-300f5ae27d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visual Testing'])[1]/preceding::span[1]</value>
      <webElementGuid>188af7c6-f8de-4d90-9b28-52c26a77d08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/preceding::span[2]</value>
      <webElementGuid>bf33a123-a09a-4663-93b7-7591f9177cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reports']/parent::*</value>
      <webElementGuid>8e394510-d78a-4a09-9a5e-1c8956307c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/a/span</value>
      <webElementGuid>4ccfeefb-82ef-4b23-b2f0-7d08fd8cd87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>3c0b9622-69d4-42bb-b045-07704e0f5837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
