<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Siliguri</name>
   <tag></tag>
   <elementGuidId>7c769825-75b6-42fd-a106-674eae48e6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='result-container']/div[3]/div[2]/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3c716675-0025-4420-968d-551adefc3f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title title-l</value>
      <webElementGuid>4e996935-07f5-43aa-bb5e-1891df0accdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Siliguri</value>
      <webElementGuid>54d99004-447f-4079-a5a1-ce5a72168e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result-container&quot;)/div[@class=&quot;row destination-list-item&quot;]/div[@class=&quot;col-md-6 col-lg-6 destination-list-desc d-flex flex-column text-center text-md-left&quot;]/a[@class=&quot;no-underline&quot;]/h2[@class=&quot;title title-l&quot;]</value>
      <webElementGuid>60196820-f5fb-421f-9d47-11dd7c1554b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='result-container']/div[3]/div[2]/a/h2</value>
      <webElementGuid>957f5ffe-5ea9-4448-8ace-d85096429804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spiti Valley'])[1]/following::h2[1]</value>
      <webElementGuid>ecddc78c-b809-4932-bae2-7c531a34356d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='West (24)'])[1]/following::h2[2]</value>
      <webElementGuid>2f373570-fc24-4df5-a027-d7992e3489f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='delhi'])[1]/preceding::h2[1]</value>
      <webElementGuid>18280d1b-00ee-4582-a2c0-ec1dae43fa40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agra'])[1]/preceding::h2[2]</value>
      <webElementGuid>f13b3e9d-be7d-4239-bf16-661b02fab7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Siliguri']/parent::*</value>
      <webElementGuid>2d9bb042-8eff-4fc9-b18e-655b81b71e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a/h2</value>
      <webElementGuid>8a4692d9-b163-4c02-a1d3-66f33a315a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Siliguri' or . = 'Siliguri')]</value>
      <webElementGuid>461450ba-d621-448e-9f69-225409d9f1b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
