<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email ID_txtEmail</name>
   <tag></tag>
   <elementGuidId>c2efbc50-18dd-4504-aeaa-577f667272f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4b591a0-3fc8-4cbf-b4b7-509b31363afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d511d3e4-0b89-4c37-a862-422ed9ac0bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-bottom-0</value>
      <webElementGuid>7f3f93ef-c446-484b-b5c5-ae85b2660f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEmail</value>
      <webElementGuid>79cb688c-0870-4a1d-822d-711c974738b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>d9582160-8337-4b53-ab83-917d1473304c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$</value>
      <webElementGuid>a3f5902d-a514-4bcc-bccc-8f12d6883e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEmail&quot;)</value>
      <webElementGuid>471642ae-4c24-4d16-a2d1-d84568fad68a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEmail']</value>
      <webElementGuid>9f88f05d-5979-4185-ab3d-53c9fe640a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-subscribe-modal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>ef7b9989-57b7-4563-b5ca-d837a497b7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>08a19b2f-a5e8-4c0a-9888-000ba619e523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'txtEmail' and @placeholder = 'Email address']</value>
      <webElementGuid>d56b1d35-e496-4593-99e0-ff33cd1571f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
